services:
  - type: web
    name: T.style
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: t_style_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: t_style_db
    databaseName: t_style_db
    user: t_style_db_user